### ISSUE TITLE
SUBIR DOCUMENTOS - Administrador

### ISSUE THREAD

**Issue by carmelormz** [ProyectoIntegrador2018/apportateen#45]
## DESCRIPCION
Yo como Administrador de ApportaTeen puedo subir n documentos a la aplicación para que esten disponibles para los usuarios en el portal.

-------------------------------------------------------------------------------------------------------

## CRITERIOS DE ACEPTACION
Se guardan y muestran en el portal de ApportaTeen los documentos subidos por el Administrador.

-------------------------------------------------------------------------------------------------------

## DETALLES IMPORTANTES NO-FUNCIONALES
Comentarios a considerarse para el desarrollo de la historia de usuario.
- Se pueden subir "n" documentos por parte del Admin. 
- Deben ser en formato "PDF"

-------------------------------------------------------------------------------------------------------

## PRIORIDAD
1 (Menor Prioridad) - 5 (Mayor Prioridad)

Prioridad: 5

-------------------------------------------------------------------------------------------------------

## ToDo
Tareas necesarias para el desarrollo de la historia de usuario.

- [x] Agregar lógica en de Firebase para subir archivos y guardarlos en FireStore

- [x] Crear Queries para guardar y obtener la liga de descarga e información del archivo en la Base de Datos

- [x] Agergar la lógica en la aplicación de ApportaTeen para mostrar los documentos subidos por el Admin. en la pantalla de Documentos
