### ISSUE TITLE
ASIGNAR ROL DE ADMINISTRADOR A USUARIOS

### ISSUE THREAD

**Issue by carmelormz** [ProyectoIntegrador2018/apportateen#48]
## DESCRIPCION
Yo como administrador puedo asignar el rol de "Administrador" a otros usuarios registrados para que puedan acceder a las diferentes funciones de este rol.

-------------------------------------------------------------------------------------------------------

## CRITERIOS DE ACEPTACION
Cuando se haga click en asignar el rol, este usuario cambia de tipo de rol y accede a las funciones y pantallas de Administrador.

-------------------------------------------------------------------------------------------------------

## DETALLES IMPORTANTES NO-FUNCIONALES
- Se pueden agregar n administradores.
- Necesita el usuario estar registrado con anterioridad.

-------------------------------------------------------------------------------------------------------

## PRIORIDAD
1 (Menor Prioridad) - 5 (Mayor Prioridad)
- Prioridad: 5

-------------------------------------------------------------------------------------------------------

## ToDo
Tareas necesarias para el desarrollo de la historia de usuario.

- [ ] Crear Pantalla de Roles

- [ ] Crear interfaz de la pantalla y el back-end de la misma.

- [ ] Crear Query para agregar usuarios a la tabla de Administrador
