### ISSUE TITLE
REVISAR LAS CONFIRMACIONES DE PAGO DE USUARIO

### ISSUE THREAD

**Issue by carmelormz** [ProyectoIntegrador2018/apportateen#50]
## DESCRIPCION
Yo como ADMINISTRADOR puedo ver los números confirmación de pago de los usuarios para llevar un control y poder confirmar si se realizó el pago del programa.

-------------------------------------------------------------------------------------------------------

## CRITERIOS DE ACEPTACION
Ver en una lista TODOS los número de confirmación de los usuarios.

-------------------------------------------------------------------------------------------------------

## DETALLES IMPORTANTES NO-FUNCIONALES
- Se debe mostrar en forma de TABLA la lista.

-------------------------------------------------------------------------------------------------------

## PRIORIDAD
Prioridad 5: Alta

-------------------------------------------------------------------------------------------------------

## ToDo

- [ ] Crear pantalla para ver los números de confirmación
- [ ] Modificar Base de Datos para incluir la columna de Num_Conf_Pago
- [ ] Crear Queries para Leer y Agregar números de confirmación de Pago
