### ISSUE TITLE
V3.0 Instrucciones precisas de uso de aplicación

### ISSUE THREAD

**Issue by tonyyasi** [ProyectoIntegrador2018/apportateen#59]
## DESCRIPCION
Como USUARIO me es posible ver las instrucciones adecuadas para el uso óptimo del sitio web

-------------------------------------------------------------------------------------------------------

## CRITERIOS DE ACEPTACION
El sitio web cuenta con instrucciones precisas de uso.

-------------------------------------------------------------------------------------------------------

## DETALLES IMPORTANTES NO-FUNCIONALES
Todas las distintas secciones deben de estar bien documentadas y explicadas

-------------------------------------------------------------------------------------------------------

## PRIORIDAD
2 - Baja

-------------------------------------------------------------------------------------------------------

## Definition of done

- No hay TODOs en el código.
- Los cambios se han probado en diferentes navegadores.
- El código ha sido aprobado por al menos otro miembro del equipo.
- Un usuario tiene acceso a las instrucciones precisas del uso de la aplicación

## Definition of ready

- Todos están de acuerdo con lo que se escribió.
- La historia de usuario fue escrita correctamente.
- El cliente aprobó el trabajo de esta historia.

## ToDo
- [ ] Enlistar las distintas partes de la aplicación que no se explican bien actualmente
- [ ] Hacer énfasis en la funcionalidad y explicar paso a paso lo que se tiene que seguir para hacer uso de la aplicación
- [ ] Validar con los usuarios que la información se encuentre claramente explicada.
- [ ] Peer review.
- [ ] Pruebas.
