### ISSUE TITLE
v3.0 Registro y pago fácil

### ISSUE THREAD

**Issue by alexelmtz** [ProyectoIntegrador2018/apportateen#62]
## DESCRIPCION
El usuario podrá solicitar una ficha de pago desde el sitio para pagar los talleres inscritos.

-------------------------------------------------------------------------------------------------------

## CRITERIOS DE ACEPTACION
Se puede solicitar una ficha de pago a través del sitio y el pago se verá reflejado en la cuenta de la organización.

-------------------------------------------------------------------------------------------------------

## DETALLES IMPORTANTES NO-FUNCIONALES
El sistema de pago debe de aceptar pesos.

-------------------------------------------------------------------------------------------------------

## PRIORIDAD
5 - Alta prioridad

-------------------------------------------------------------------------------------------------------

## Definition of done

- No hay TODOs en el código.
- Los cambios se han probado en diferentes navegadores.
- El código ha sido aprobado por al menos otro miembro del equipo.
- Se genera una ficha de pago automáticamente cuando el usuario la solicita.

## Definition of ready

- Todos están de acuerdo con lo que se escribió.
- La historia de usuario fue escrita correctamente.
- El cliente aprobó el trabajo de esta historia.

## ToDo

- [x] Generar la ficha de pago con los datos proporcionados.
- [x] Agregar ficha de pago a flujo de pago.
- [x] Cambiar flujo al hacer login.
- [x] Crear nueva seccion en panel de admin para marcar pagado y pendiente.
- [x] Pruebas de funcionamiento.
- [x] Peer review.
