### ISSUE TITLE
Fácil control a datos de participantes

### ISSUE THREAD

**Issue by alexelmtz** [ProyectoIntegrador2018/apportateen#63]
## DESCRIPCION
Los participantes deben de poder inscribirse a varios cursos a la vez y deberán de poder ver fácilmente los datos de su cuenta.
-------------------------------------------------------------------------------------------------------

## CRITERIOS DE ACEPTACION
Un usuario se puede inscribir a más de un curso a la vez siempre y cuando no se empalmen.

-------------------------------------------------------------------------------------------------------

## DETALLES IMPORTANTES NO-FUNCIONALES
Un usuario se puede inscribir a más de un curso siempre y cuando no sean al mismo tiempo.

-------------------------------------------------------------------------------------------------------

## PRIORIDAD
3 - Prioridad media

-------------------------------------------------------------------------------------------------------

## ToDo
- [ ] Crear página para ver datos de los usuarios y cursos inscritos.
- [ ] Agregar funcionalidad de que un usuario pueda inscribir más de un curso.
- [ ] Agregar restricción de no más de un curso inscrito al mismo tiempo por un usuario.
